CD_MAPPING: dict[str, str] = {
    "rebadeaux_1": "CD #35 (Rebadeaux)",
    "harrowgate_1": "CD #36 (Harrowgate)",
    "rebadeaux_2": "CD #40 (Rebadeaux)",
    "shivington_1": "CD #41 (Shivington)",
    "prawn_court_1": "CD #39 (Prawn Court)",
    "stoughton_1": "CD #45 (Stoughton)",
    "stoughton_2": "CD #47 (Stoughton)",
    "southern_cross_1": "CD #44 (Southern Cross)",
    "huntersfield_1": "CD #48 (Huntersfield)",
    "wardill_airport_1": "CD #7 (Wardill Airport)",
    "wardill_airport_2": "CD #8 (Wardill Airport)",
    "ezpata_1": "CD #43 (Ezpata)",
    "athos_bay_1": "CD #38 (Athos Bay)",
    "mission_beach_1": "CD #37 (Mission Beach)",
    "little_shanghai_1": "CD #42 (Little Shanghai)",
    "stilwater_university_1": "CD #49 (Stilwater University)",
    "stilwater_university_2": "CD #50 (Stilwater University)",
    "frat_row_1": "CD #46 (Frat Row)",
    "stilwater_nuclear_1": "CD #11 (Stilwater Nuclear)",
    "stilwater_nuclear_2": "CD #10 (Stilwater Nuclear)",
    "stilwater_nuclear_3": "CD #9 (Stilwater Nuclear)",
    "stilwater_nuclear_4": "CD #6 (Stilwater Nuclear)",
    "hangman_s_wharf_1": "CD #1 (Hangman's Wharf)",
    "hangman_s_wharf_2": "CD #4 (Hangman's Wharf)",
    "stilwater_penitentiary_1": "CD #2 (Stilwater Penitentiary)",
    "stilwater_penitentiary_2": "CD #5 (Stilwater Penitentiary)",
    "stilwater_penitentiary_3": "CD #3 (Stilwater Penitentiary)",
    "no_district_1": "CD #12",
    "brighton_1": "CD #33 (Brighton)",
    "brighton_2": "CD #34 (Brighton)",
    "brighton_3": "CD #13 (Brighton)",
    "adept_way_1": "CD #32 (Adept Way)",
    "amberbrook_1": "CD #31 (Amberbrook)",
    "amberbrook_2": "CD #30 (Amberbrook)",
    "amberbrook_3": "CD #29 (Amberbrook)",
    "centennial_beach_1": "CD #28 (Centennial Beach)",
    "centennial_beach_2": "CD #27 (Centennial Beach)",
    "stilwater_boardwalk_1": "CD #25 (Stilwater Boardwalk)",
    "stilwater_boardwalk_2": "CD #26 (Stilwater Boardwalk)",
    "misty_lane_1": "CD #18 (Misty Lane)",
    "new_hennequet_1": "CD #17 (New Hennequet)",
    "quinbecca_1": "CD #16 (Quinbecca)",
    "elysian_fields_1": "CD #14 (Elysian Fields)",
    "misty_lane_2": "CD #15 (Misty Lane)",
    "misty_lane_3": "CD #19 (Misty Lane)",
    "misty_lane_4": "CD #21 (Misty Lane)",
    "tidal_spring_1": "CD #20 (Tidal Spring)",
    "tidal_spring_2": "CD #22 (Tidal Spring)",
    "nob_hill_1": "CD #23 (Nob Hill)",
    "stilwater_boardwalk_3": "CD #24 (Stilwater Boardwalk)",
}

CD_IDS = {
    **{name: 500 + i for i, name in enumerate(CD_MAPPING.values())},
}

STYLE_LEVEL_LOCATIONS = [f"Style Level - Level {i + 1}" for i in range(10)]

STYLE_LEVEL_IDS = {**{name: 600 + i for i, name in enumerate(STYLE_LEVEL_LOCATIONS)}}

TAGS_MAPPING: dict[str, str] = {
    "tag_01": "Tag #1",
    "tag_02": "Tag #2",
    "tag_03": "Tag #3",
    "tag_04": "Tag #4",
    "tag_05": "Tag #5",
    "tag_06": "Tag #6",
    "tag_07": "Tag #7",
    "tag_08": "Tag #8",
    "tag_09": "Tag #9",
    "tag_10": "Tag #10",
    "tag_11": "Tag #11",
    "tag_12": "Tag #12",
    "tag_13": "Tag #13",
    "tag_14": "Tag #14",
    "tag_15": "Tag #15",
    "tag_16": "Tag #16",
    "tag_17": "Tag #17",
    "tag_18": "Tag #18",
    "tag_19": "Tag #19",
    "tag_20": "Tag #20",
    "tag_21": "Tag #21",
    "tag_22": "Tag #22",
    "tag_23": "Tag #23",
    "tag_24": "Tag #24",
    "tag_25": "Tag #25",
    "tag_26": "Tag #26",
    "tag_27": "Tag #27",
    "tag_28": "Tag #28",
    "tag_29": "Tag #29",
    "tag_30": "Tag #30",
    "tag_31": "Tag #31",
    "tag_32": "Tag #32",
    "tag_33": "Tag #33",
    "tag_34": "Tag #34",
    "tag_35": "Tag #35",
    "tag_36": "Tag #36",
    "tag_37": "Tag #37",
    "tag_38": "Tag #38",
    "tag_39": "Tag #39",
    "tag_40": "Tag #40",
    "tag_41": "Tag #41",
    "tag_42": "Tag #42",
    "tag_43": "Tag #43",
    "tag_44": "Tag #44",
    "tag_45": "Tag #45",
    "tag_46": "Tag #46",
    "tag_47": "Tag #47",
    "tag_48": "Tag #48",
    "tag_49": "Tag #49",
    "tag_50": "Tag #50",
}

TAGS_IDS = {
    **{name: 650 + i for i, name in enumerate(TAGS_MAPPING.values())},
}
