CD_MAPPING: dict[str, str] = {
    "rebadeaux_1": "CD #35 - Rebadeaux, behind Kanto",
    "harrowgate_1": "CD #36 - Harrowgate, next to Hitman under pedestrian bridge",
    "rebadeaux_2": "CD #40 - Rebadeaux, behind Teenay, up the stairs",
    "shivington_1": "CD #41 - Shivington, near blown up house next to Saints HQ",
    "prawn_court_1": "CD #39 - Prawn Court, behind ruined Transportation Center",
    "stoughton_1": "CD #45 - Stoughton, under the Halloway's Towing sign",
    "stoughton_2": "CD #47 - Stoughton, wooden pier next to Brotherhood hideout",
    "southern_cross_1": "CD #44 - Southern Cross, big field, behind blue barrels, next to Hitman",
    "huntersfield_1": "CD #48 - Huntersfield, big statue near skyscraper",
    "wardill_airport_1": "CD #7 - Wardill Airport, inside terminal building down the stairs to gate C1",
    "wardill_airport_2": "CD #8 - Wardill Airport, balcony of destroyed building next to destroyed plane next to the runway",
    "ezpata_1": "CD #43 - Ezpata, entrance to undeground garage near the street",
    "athos_bay_1": "CD #38 - Athos Bay, end of pier with statue",
    "mission_beach_1": "CD #37 - Mission Beach, road tunnel behind Philips Building",
    "little_shanghai_1": "CD #42 - Little Shanghai, catwalk between building with fire exit stairs and building with neon Chinese text",
    "stilwater_university_1": "CD #49 - Stilwater University, walking path around tree in the corner of the district",
    "stilwater_university_2": "CD #50 - Stilwater University, Marshall Winslow Observatory Balcony",
    "frat_row_1": "CD #46 - Frat Row, dumpster behind building opposite of Demo Derby building",
    "stilwater_nuclear_1": "CD #11 - Stilwater Nuclear, on rooftop near brown dome",
    "stilwater_nuclear_2": "CD #10 - Stilwater Nuclear, inside reacter marked Water Tunnel 2",
    "stilwater_nuclear_3": "CD #9 - Stilwater Nuclear, inside water tunnel",
    "stilwater_nuclear_4": "CD #6 - Stilwater Nuclear, front of the ship in the docks",
    "hangman_s_wharf_1": "CD #1 - Hangman's Wharf, rooftop of building at docks",
    "hangman_s_wharf_2": "CD #4 - Hangman's Wharf, courtyard of house, next to Hitman",
    "stilwater_penitentiary_1": "CD #2 - Stilwater Penitentiary, guard tower overlooking Fight Club",
    "stilwater_penitentiary_2": "CD #5 - Stilwater Penitentiary, lighthouse balcony",
    "stilwater_penitentiary_3": "CD #3 - Stilwater Penitentiary, dirt road under lighthouse near ramp",
    "no_district_1": "CD #12 - inside bridge column of the bridge with train tracks",
    "brighton_1": "CD #33 - Brighton, pathwalk behind dome with bright lights",
    "brighton_2": "CD #34 - Brighton, downtown glass walkway",
    "brighton_3": "CD #13 - Brighton, high rise garden",
    "adept_way_1": "CD #32 - Adept Way, pier near fountain, down the stairs",
    "amberbrook_1": "CD #31 - Amberbrook, inside parking garage",
    "amberbrook_2": "CD #30 - Amberbrook, right side pier",
    "amberbrook_3": "CD #29 - Amberbrook, left side interior",
    "centennial_beach_1": "CD #28 - Centennial Beach, wooden balcony near pier",
    "centennial_beach_2": "CD #27 - Centennial Beach, entrance to underground car park near Asian restaurant",
    "stilwater_boardwalk_1": "CD #25 - Stilwater Boardwalk, Volition offices",
    "stilwater_boardwalk_2": "CD #26 - Stilwater Boardwalk, inside lighthouse",
    "misty_lane_1": "CD #18 - Misty Lane, inside pool of rundown mansion",
    "new_hennequet_1": "CD #17 - New Hennequet, rooftop of Recreational Center",
    "quinbecca_1": "CD #16 - Quinbecca, inside in construction house",
    "elysian_fields_1": "CD #14 - Elysian Fields, on pier near water",
    "misty_lane_2": "CD #15 - Misty Lane, under collapsed highway stunt jump near trailer park",
    "misty_lane_3": "CD #19 - Misty Lane, apartments up the stairs",
    "misty_lane_4": "CD #21 - Misty Lane, rooftop of Technically Legal",
    "tidal_spring_1": "CD #20 - Tidal Spring, dam pier under the bridge",
    "tidal_spring_2": "CD #22 - Tidal Spring, alley behind IllWireless building",
    "nob_hill_1": "CD #23 - Nob Hill, behind Impressions",
    "stilwater_boardwalk_3": "CD #24 - Stilwater Boardwalk, under waterfall behind Ronin casino",
}

CD_IDS = {
    **{name: 500 + i for i, name in enumerate(CD_MAPPING.values())},
}
