TRAP_NOTORIETY_ITEMS = [
    "Trap: Max Police Notoriety",
    "Trap: Max Ronin Notoriety",
    "Trap: Max Brotherhood Notoriety",
    "Trap: Max Samedi Notoriety",
]

TRAP_CHEATS = [
    "Trap: Heavy Rain",
    "Trap: Light Rain",
    "Trap: Thunderstorm",
]

TRAP_ITEMS = TRAP_CHEATS + TRAP_NOTORIETY_ITEMS

MONEY_ITEM_NAMES = ["$1,000", "$5,000", "$10,000"]

WEAPON_ITEM_NAMES = [
    # Melee
    "Weapon: Pimp Slap",
    "Weapon: Samurai Sword",
    "Weapon: Pepper Spray",
    "Weapon: Stun Gun",
    "Weapon: Nightstick",
    "Weapon: Knife",
    "Weapon: Baseball Bat",
    "Weapon: Machete",
    "Weapon: Sledgehammer",
    "Weapon: Chainsaw",
    # Pistols
    "Weapon: VICE 9",
    "Weapon: Kobra",
    "Weapon: NR4",
    "Weapon: GDHC .50",
    "Weapon: .44 Shepherd",
    # SMGs
    "Weapon: T3K Urban",
    "Weapon: GAL 43",
    "Weapon: SKR-9 Threat",
    # Shotguns
    "Weapon: AS14 Hammer",
    "Weapon: Tombstone",
    "Weapon: XS-2 Ultimax",
    "Weapon: 12 Gauge",
    "Weapon: Pimp Cane",
    # Rifles
    "Weapon: K6 Krukov",
    "Weapon: AR-50 XMAC",
    "Weapon: AR200 SAW",
    # Special
    "Weapon: McManus 2010",
    "Weapon: RPG Launcher",
    "Weapon: Annihilator RPG",
    # Thrown
    "Weapon: Flashbang",
    "Weapon: Molotov Cocktail",
    "Weapon: Pipe Bomb",
    "Weapon: Satchel Charge",
    "Weapon: Hand Grenade",
]

USEFUL_UNLOCKABLES = [
    "Weapon Cache: Kobra Pistols",
    "Weapon Cache: GAL 43",
    "Weapon Cache: Minigun",
    "Weapon Cache: Pimpcane",
    "Weapon Cache: AR-50 XMAC Special",
    "Weapon Cache: Flamethrower",
    "Weapon Cache: Annihilator RPG",
    "Weapon Cache: Infinite Pistol Ammo",
    "Weapon Cache: Infinite SMG Ammo",
    "Weapon Cache: Infinite Shotgun Ammo",
    "Weapon Cache: Infinite Rifle Ammo",
    "Upgraded Sprint",
    "Infinite Sprint",
    "Health Generation x2",
    "Health Generation x3",
    "Vehicle: Ultor Tornado",
    "Vehicle: Race Car Bezier",
    "Reduced Fall Damage (100%)",
]

FILLER_UNLOCKABLES = [
    "Vehicle: News Helicopter",
    "Vehicle: Saints Oppressor",
    "Vehicle: Buggy",
    "Vehicle: Saints Combine",
    "Vehicle: Saints Tow Truck",
    "Vehicle: Saints Fire Truck",
    "Vehicle: Saints Ambulance",
    "Vehicle: Saints Taxi",
    "Vehicle: Saints Sabretooth",
    "Vehicle: Saints Skipper",
    "Vehicle: Saints Wolverine",
    "Vehicle: Julius's Eiswolf",
    "Vehicle: Donnie's Voxel",
    "Vehicle: The General's Bulldog",
    "Vehicle: Maero's Monster Truck",
    "Vehicle: Akuji's Kaneda",
    "Vehicle: Ultor APC",
    "Vehicle: Medical Helicopter",
    "Vehicle: Septic Truck",
    "Vehicle: Unique ATV",
    "Vehicle: Unique Bootlegger",
    "Vehicle: Unique Phoenix",
    "Vehicles: Escort Vehicles (Ethel, Socialite)",
    "Vehicles: Demolition Derby Vehicles",
    "Weapon Cache: Shock Paddles",
    "Weapon Cache: Pepper Spray",
    "Weapon Cache: Chainsaw",
    "Weapon Cache: Hand Grenades",
    "Weapon Cache: Satchel Charges",
    "Mechanic Discount (5%)",
    "Mechanic Discount (15%)",
    "Mechanic Discount (75%)",
    "Improved Melee Damage (15%)",
    "Improved Melee Damage (30%)",
    "Improved Weapon Accuracy (5%)",
    "Improved Weapon Accuracy (15%)",
    "Police Notoriety Reduced (5%)",
    "Police Notoriety Reduced (15%)",
    "Samedi Notoriety Reduced (5%)",
    "Samedi Notoriety Reduced (15%)",
    "Brotherhood Notoriety Reduced (5%)",
    "Brotherhood Notoriety Reduced (15%)",
    "Ronin Notoriety Reduced (5%)",
    "Ronin Notoriety Reduced (15%)",
    "Reduced Vehicle Damage (5%)",
    "Reduced Vehicle Damage (15%)",
    "Reduced Bullet Damage (5%)",
    "Reduced Bullet Damage (15%)",
    "Reduced Explosion Damage (5%)",
    "Reduced Explosion Damage (15%)",
    "Weapon Store Discount (5%)",
    "Weapon Store Discount (15%)",
    "Food Discount (5%)",
    "Food Discount (15%)",
    "Food Discount (100%)",
    "Clothing Discount (5%)",
    "Clothing Discount (15%)",
    "Music Discount (100%)",
    "Crib Customization Discount (5%)",
    "Crib Customization Discount (15%)",
    "Melee Combat Style - Ronin",
    "Melee Combat Style - Brotherhood",
    "Melee Combat Style - Sons of Samedi",
    "Clothing: Avenger Jacket",
    "Clothing: Fireman Outfit",
    "Clothing: Pimp Outfit",
    "Clothing: Fire Fighter Suit",
    "Clothing: Paintball Mask",
    "Clothing: Cowboy Hat",
    "Clothing: Traffic Cone Hat",
    "Clothing: Zombie Mask",
    "Gang Vehicles: Brotherhood",
    "Gang Vehicles: Ronin",
    "Gang Vehicles: Sons of Samedi",
]


CHEAT_ITEMS = [
    "Time: Midnight",
    "Time: Noon",
    "Weather: Clear Skies",
    "Weather: Overcast",
    "Weather: Restore Normal Cycle",
    "Remove Police Notoriety",
    "Remove Gang Notoriety",
    "Max Health",
    "Car Repair",
    "Vehicle: Five-O",
    "Vehicle: Peewee",
    "Vehicle: Gyro Daddy",
    "Vehicle: Destroy (UFO)",
    "Vehicle: Miami",
    "Vehicle: Attrazione",
    "Vehicle: Fire Truck",
    "Vehicle: Oring",
    "Vehicle: Stilwater Municipal",
    "Vehicle: Raycaster",
    "Vehicle: Superiore",
    "Vehicle: Reaper",
    "Vehicle: The Job",
    "Vehicle: Vortex",
    "Vehicle: Zenith",
    "Vehicle: Titan",
    "Vehicle: Quota",
    "Vehicle: Quasar",
    "Vehicle: Phoenix",
    "Vehicle: Longhauler",
    "Vehicle: Mongoose",
    "Vehicle: Justice",
    "Vehicle: FBI",
    "Vehicle: Hollywood",
    "Vehicle: Melbourne",
    "Vehicle: Sandstorm",
    "Vehicle: Ambulance",
    "Vehicle: Python",
    "Vehicle: Anchor",
    "Vehicle: Eiswolf",
]
